version: '3'

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge


services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - default.env
    networks: 
      - db_network
  web:
    build:
      context: ./deans-api
    # command: bash -c "python manage.py collectstatic --no-input && gunicorn --chdir deans_api --log-level=debug --bind :8000 deans_api.wsgi:application"
    command: bash -c "python manage.py collectstatic --no-input; python3 manage.py makemigrations; python3 manage.py migrate; python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - default.env
    volumes:
      - ./deans-api:/code
      - static_volume:/static
    expose:
      - 8000
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    networks: 
      - db_network
      - nginx_network
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./nginx-config/conf.d:/etc/nginx/conf.d
      - static_volume:/static
    env_file:
      - default.env
    depends_on:
      - web
    networks:
      - nginx_network
  cron:
    build:
      context: ./deans-api
    command: bash -c "python3 /cron/cron.py"
    env_file:
      - default.env
    volumes:
      - ./cron:/cron
      - ./deans-api:/code
    depends_on:
      - web
    networks: 
      - db_network
      - nginx_network

volumes:
  static_volume: