version: '3'

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge


services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    networks: 
      - db_network
  web:
    build:
      context: ./deans-api
    command:  bash -c "python manage.py collectstatic --no-input && gunicorn --chdir deans_api --bind :8000 deans_api.wsgi:application"
    volumes:
      - ./deans-api:/code
      - static_volume:/static
    expose:
      - 8000
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    networks: 
      - db_network
      - nginx_network
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./nginx-config/conf.d:/etc/nginx/conf.d
      - static_volume:/code/deans_api/static
    depends_on:
      - web
    networks:
      - nginx_network

volumes:
  static_volume: